### ISSUE TITLE
Unable to load f1.h5

### ISSUE THREAD

**Issue by rvignav** [kesaroid/Glaucoma-Detection#4]
I trained the CNN and it worked well over all 100 epochs, but when I ran `python GUI.py` I got the following error:
```
Traceback (most recent call last):
  File "GUI.py", line 11, in <module>
    model = load_model('f1.h5')
  File "/usr/local/lib/python2.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "/usr/local/lib/python2.7/site-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (file signature not found)
```
Not sure why I am unable to load the weights file.

**Comment by rvignav** [comment]
I solved the error: replace `model = load_model('f1.h5')` with 
```h5file =  "dataweightsvha.h5"
with h5py.File(h5file,'r') as fid:
     model = load_model(fid)
```
